version: '3.1'

services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: database
    volumes:
      - "./mysql:/var/lib/mysql"
    ports:
      ["3306:3306"]
    expose:
      - 3306